title: Cicer.GitHub.com
description: 
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
  
deploy:
  type: git
  repository: git@github.com:mrcicer/mrcicer.github.io.git
  branch: master